# -*- coding: utf-8 -*-
"""Copy of perceptron.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R3lpzVD0LLbC5Y_ZNwAIyKvT9zZ-mxfP
"""

import numpy as np

def sigmoid(x):
  return 1.0 / (1 + np.exp(-x))

class Perceptron():
  def __init__(self, n_inputs=4, n_hidden=8, n_outputs=3):
    # Sinapses
    self.w_ih = np.random.random((n_hidden, n_inputs))
    self.w_ho = np.random.random((n_outputs, n_hidden))
    # Biases
    self.b_hid = np.random.random((n_hidden, 1))
    self.b_out =  np.random.random((n_outputs, 1))
  def compute(self, inputs):
    # Garante que a entrada seja um vetor coluna
    inputs = np.reshape(inputs,(len(inputs),1))
    # Calcula as ativações, camada por camada
    self.s_hid = np.dot(self.w_ih, inputs) + self.b_hid
    self.z_hid = sigmoid(self.s_hid)
    self.s_out = np.dot(self.w_ho, self.z_hid) + self.b_out
    self.z_out = sigmoid(self.s_out)
    return self.z_out

p = Perceptron()
p.compute([1,2,3,4])