# -*- coding: utf-8 -*-
"""Copy of simple_neuron.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gO0stpoOCY6VMK_NJn_ZWMeI9mDQE8B6
"""

import numpy as np
from matplotlib import pyplot as plt

def sigmoid(x):
  return 1.0 / (1 + np.exp(-x))

x = np.linspace(-5.0, 5.0)
y = sigmoid(x)

plt.plot(x,y)

class Neuron:
  def __init__(self, input_size=3):
    self.w = np.random.random(input_size)
    self.b = -0.5
  def compute(self, inputs):
    s = np.dot(self.w,inputs) + self.b
    z = sigmoid(s)
    return z

n = Neuron()
n.compute([1,2,3])